server:
  port: 0

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registryFetchIntervalSeconds: 5

#spring:
#  rabbitmq:
#    addresses: ${vcap.services.${PREFIX:}rabbitmq.credentials.uri:amqp://${RABBITMQ_HOST:localhost}:${RABBITMQ_PORT:5672}}

logging:
  level:
    com.netflix.discovery: 'OFF'

---
spring:
  profiles: mysql
  datasource:
    url: jdbc:mysql://localhost/test
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
