info:
  component: API Gateway
  
server:
  port: 8765
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
      restaurants:
        path: /restaurants/**
        serviceId: restaurants
        stripPrefix: false
      ratings:
        path: /ratings/**
        serviceId: ratings
        stripPrefix: false

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
